#! /bin/bash

echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u rs22 --password-stdin
docker tag  docker.pkg.github.com/leichtbau/wifi-connect/wifi-connect-$ARCH:latest docker.pkg.github.com/leichtbau/wifi-connect/wifi-connect-$ARCH:$TRAVIS_TAG
docker push docker.pkg.github.com/leichtbau/wifi-connect/wifi-connect-$ARCH:$TRAVIS_TAG
